name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: prep
      run: make prep
    - name: make release
      run: make release
    - name: make run
      run: make run
    - name: make test
      run: make test
